"""init

Revision ID: 6c700992b858
Revises: 
Create Date: 2026-07-11 11:12:00.860277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c700992b858'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name_ko', sa.String(length=50), nullable=False),
    sa.Column('name_en', sa.String(length=80), nullable=True),
    sa.Column('type', sa.String(length=12), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.CheckConstraint("type IN ('index','indicator','sector','theme')", name='ck_analysis_categories_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('analysis_presets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name_ko', sa.String(length=50), nullable=False),
    sa.Column('persona_text', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('document_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_type', sa.String(length=10), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('tickers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('facts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source_type IN ('news','report','paste')", name='ck_document_analyses_source_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_table('market_overviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('briefing_date', sa.Date(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('indices', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sector_moves', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('briefing_date')
    )
    op.create_table('sectors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_ko', sa.String(length=50), nullable=False),
    sa.Column('name_en', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('investor_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("investor_type IN ('stable','balanced','aggressive')", name='ck_users_investor_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('analysis_renders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_analysis_id', sa.Integer(), nullable=False),
    sa.Column('preset_id', sa.Integer(), nullable=False),
    sa.Column('category_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('depth', sa.String(length=10), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_analysis_id'], ['document_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['preset_id'], ['analysis_presets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_analysis_id', 'preset_id', 'category_codes', 'depth', 'language', name='uq_analysis_renders_combo')
    )
    op.create_table('stocks',
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('name_ko', sa.String(length=100), nullable=True),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('user_preferences',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('default_preset_id', sa.Integer(), nullable=True),
    sa.Column('default_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('depth', sa.String(length=10), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.CheckConstraint("depth IN ('brief','standard','deep')", name='ck_user_preferences_depth'),
    sa.ForeignKeyConstraint(['default_preset_id'], ['analysis_presets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('daily_briefings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('briefing_date', sa.Date(), nullable=False),
    sa.Column('sentiment', sa.String(length=10), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('positive_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('negative_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('watch_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('today_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("sentiment IN ('positive','neutral','negative')", name='ck_daily_briefings_sentiment'),
    sa.ForeignKeyConstraint(['ticker'], ['stocks.ticker'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'briefing_date', name='uq_daily_briefings_ticker_date')
    )
    op.create_index(op.f('ix_daily_briefings_ticker'), 'daily_briefings', ['ticker'], unique=False)
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.String(length=10), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['stocks.ticker'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_news_articles_ticker'), 'news_articles', ['ticker'], unique=False)
    op.create_table('price_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('close', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('change_pct', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['stocks.ticker'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'trade_date', name='uq_price_snapshots_ticker_date')
    )
    op.create_index(op.f('ix_price_snapshots_ticker'), 'price_snapshots', ['ticker'], unique=False)
    op.create_table('stock_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['stocks.ticker'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_comments_ticker'), 'stock_comments', ['ticker'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['stocks.ticker'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ticker', name='uq_watchlists_user_ticker')
    )
    op.create_index(op.f('ix_watchlists_ticker'), 'watchlists', ['ticker'], unique=False)
    op.create_index(op.f('ix_watchlists_user_id'), 'watchlists', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlists_user_id'), table_name='watchlists')
    op.drop_index(op.f('ix_watchlists_ticker'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_stock_comments_ticker'), table_name='stock_comments')
    op.drop_table('stock_comments')
    op.drop_index(op.f('ix_price_snapshots_ticker'), table_name='price_snapshots')
    op.drop_table('price_snapshots')
    op.drop_index(op.f('ix_news_articles_ticker'), table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index(op.f('ix_daily_briefings_ticker'), table_name='daily_briefings')
    op.drop_table('daily_briefings')
    op.drop_table('user_preferences')
    op.drop_table('stocks')
    op.drop_table('analysis_renders')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('sectors')
    op.drop_table('market_overviews')
    op.drop_table('document_analyses')
    op.drop_table('analysis_presets')
    op.drop_table('analysis_categories')
    # ### end Alembic commands ###
